version: '3.8'

services:
    redis:
      image: redis:latest
      restart: always
      ports:
        - 6379:6379

    postgres:
      image: postgres:latest
      restart: unless-stopped
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
      volumes:
        - ./database:/var/lib/postgresql/data

    example-backend:
      build:
        context: ./example-backend
        dockerfile: Dockerfile
      environment:
        - REQUEST_ORIGIN=http://localhost:4999
        - PORT=8080
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DATABASE=postgres
      ports:
        - 8080:8080
      container_name: example-backend
      depends_on: 
        - redis
        - postgres

    example-frontend:
      build:
        context: ./example-frontend
        dockerfile: Dockerfile
      ports:
        - 4999:4999
      container_name: example-frontend
      depends_on: 
        - example-backend