version: '3.8'

services:
    example-backend:
      build:
        context: ./example-backend
        dockerfile: Dockerfile
      environment:
        - REQUEST_ORIGIN=http://localhost:4999
        - PORT=8080
      ports:
        - 8080:8080
      container_name: example-backend

    example-frontend:
      build:
        context: ./example-frontend
        dockerfile: Dockerfile
      ports:
        - 4999:4999
      container_name: example-frontend
      depends_on: 
        - example-backend